#!/bin/sh

if [ -f $1 ]; then
  e=$(awk '/(feat|fix|docs|style|refactor|test|chore): .{1}/' $1)
  if [ ${#e} -gt 0 ]; then
    echo ""
    echo "Commit message varified!"
	exit 0
  fi
fi
echo ""
echo "Your commit message format is invalid!"
echo "Please try again and commit like \"type: subject\"."
echo ""
echo "The argument \"subject\" is a short description for this commit, the argument \"type\" should be one of them below:"
echo ""
echo "1. feat:     A new feature"
echo "2. fix:      A bug fix"
echo "3. docs:     Documentation only changes"
echo "4. style:    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"
echo "5. refactor: A code change that neither fixes a bug nor adds a feature"
echo "6. test:     A code change that improves performance"
echo "7. chore:    Adding missing tests or correcting existing tests"
echo ""
exit 1