version: "3"

services:
    jaeger-collector:
        image: jaegertracing/jaeger-collector:1.13
        ports:
            - "14269:14269"
            - "14268:14268"
            - "14267:14267"
            - "9411:9411"
        networks:
            - jaeger
        restart: on-failure
        environment:
            - SPAN_STORAGE_TYPE=elasticsearch
        command: [
            "--es.server-urls=${ES_SERVER_URLS}",
        ]

    jaeger-agent:
        image: jaegertracing/jaeger-agent:1.13
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
        networks:
            - jaeger
        restart: on-failure
        environment:
            - SPAN_STORAGE_TYPE=elasticsearch
        depends_on:
            - jaeger-collector
        command: [
            "--collector.host-port=jaeger-collector:14267"
        ]

              
    jaeger-query:
        image: jaegertracing/jaeger-query:1.13
        environment:
            - SPAN_STORAGE_TYPE=elasticsearch
        ports:
            - "16686:16686"
            - "16687:16687"
        networks:
            - jaeger
        restart: on-failure
        command: [
            "--es.server-urls=${ES_SERVER_URLS}"
        ]
# depends_on:
#       - jaeger-collector

networks:
    jaeger:
        driver: bridge
